apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: finflow-prod
  labels:
    app: payments-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: payments-service
