# Elasticsearch values for Helm chart
# This file configures the Elasticsearch deployment

# Global settings
global:
  clusterName: finflow-elasticsearch
  nodeGroup: master

# Master node configuration
master:
  replicas: 3
  heapSize: "1g"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    storageClass: standard
    size: 50Gi
  
# Data node configuration
data:
  replicas: 3
  heapSize: "2g"
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  persistence:
    enabled: true
    storageClass: standard
    size: 100Gi

# Client node configuration
client:
  replicas: 2
  heapSize: "1g"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  
# Security settings
security:
  enabled: true
  elasticPassword: "${elasticsearch_password}"
  
# Ingress configuration
ingress:
  enabled: false

# Service configuration
service:
  type: ClusterIP

# Monitoring configuration
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s

# Snapshot repository configuration
snapshotRepository:
  enabled: true
  type: s3
  settings:
    bucket: finflow-elasticsearch-snapshots
    region: us-west-2
    compress: true
