apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: finflow-prod
  labels:
    app: analytics-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: analytics-service
