---
# Handlers for monitoring role

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: Restart Fluentd
  systemd:
    name: td-agent
    state: restarted
