apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: accounting-db
  namespace: finflow-prod
  labels:
    app: accounting-db
    component: database
spec:
  serviceName: accounting-db
  replicas: 1
  selector:
    matchLabels:
      app: accounting-db
  template:
    metadata:
      labels:
        app: accounting-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: accounting-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accounting-db-credentials
              key: password
        - name: POSTGRES_DB
          value: accounting
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: accounting-db-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      securityContext:
        fsGroup: 999
  volumeClaimTemplates:
  - metadata:
      name: accounting-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
