apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: finflow-prod
  labels:
    app: auth-db
    component: database
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: auth-db
