apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: finflow-prod
  labels:
    app: kafka
    component: messaging
spec:
  clusterIP: None
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
  selector:
    app: kafka
