apiVersion: v1
kind: Service
metadata:
  name: credit-engine
  namespace: finflow-prod
  labels:
    app: credit-engine
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: credit-engine
